//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : MakeMoney
	/// Data Source    : MakeMoney
	/// Server Version : 3.24.0
	/// </summary>
	public partial class MakeMoneyDB : LinqToDB.Data.DataConnection
	{
		public ITable<InstrumentPrice> InstrumentPrices { get { return this.GetTable<InstrumentPrice>(); } }

		public MakeMoneyDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MakeMoneyDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("InstrumentPrice")]
	public partial class InstrumentPrice
	{
		[Column, NotNull] public string   Name                 { get; set; } // varchar(6)
		[Column, NotNull] public DateTime Date                 { get; set; } // date
		[Column, NotNull] public decimal  ClosingPrice { get; set; } // decimal
	}
}

#pragma warning restore 1591
