//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : StrategyTester
	/// Data Source    : StrategyTester
	/// Server Version : 3.40.1
	/// </summary>
	public partial class StrategyTesterDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<InstrumentPrice> InstrumentPrices { get { return this.GetTable<InstrumentPrice>(); } }

		#endregion

		#region .ctor

		public StrategyTesterDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public StrategyTesterDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public StrategyTesterDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public StrategyTesterDB(DataOptions<StrategyTesterDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="InstrumentPrice")]
	public partial class InstrumentPrice
	{
		[PrimaryKey(0), NotNull] public string   Name                 { get; set; } // varchar(6)
		[PrimaryKey(1), NotNull] public DateTime Date                 { get; set; } // DAte
		[Column,        NotNull] public decimal  AdjustedClosingPrice { get; set; } // decimal(28, 6)
	}

	public static partial class TableExtensions
	{
		public static InstrumentPrice Find(this ITable<InstrumentPrice> table, string Name, DateTime Date)
		{
			return table.FirstOrDefault(t =>
				t.Name == Name &&
				t.Date == Date);
		}
	}
}
